dist: trusty
sudo: require

branches:
  only:
  - master

language: cpp

compiler:
    - g++
    - clang++

os:
    - linux
    - osx

addons: 
    apt: 
        sources:
            - ubuntu-toolchain-r-test
        packages:
        - gcc
        - g++
        - cmake
        - clang-3.3
            
before_script:
    - cd R6pp
    - mkdir build
    - cd build
    - cmake ..
      
script:
    make
    
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
    