dist: trusty
sudo: require

branches:
  only:
  - master

language: cpp
compiler: 
    - g++
    - clang++

os:
    - windows
    - osx
    - linux
    
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake
      - clang-3.3
      
before_script:
    - cd R6pp
    - mkdir build
    - cd build
    - cmake ..
      
script:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then MSBuild /nologo /t:ProjectName:Build R6pp.sln; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make; fi
    