dist: trusty
sudo: require

branches:
  only:
  - master

language: cpp

matrix:
    include:
        - os: windows
           compiler: MSBuild
        - os: linux
           compiler:
           - g++
           - clang++
           addons:
            apt:
             sources:
             - ubuntu-toolchain-r-test
             packages:
             - gcc
             - g++
             - cmake
             - clang-3.3
        - os: osx
         compiler:
         - g++
         - clang++
         addons:
          homebrew:
           packages:
            -openssl
            
before_script:
    - cd R6pp
    - mkdir build
    - cd build
    - cmake ..
      
script:
    make
    